### ISSUE TITLE
Паллетоукладчик

### ISSUE THREAD

**Issue by tanya525625** [Aizeren/Tikkurila-project#14]
Каким образом будет происходить укладывание паллет: автоматически или вручную (физический труд человека)?

**Comment by tanya525625** [comment]
Пришли к выводу, что процесс будет происходить автоматически. Как будет осуществляться укладывание паллет? Роботом или паллетоукладчиком?

**Comment by tanya525625** [comment]
Укладывание паллет будет происходить автоматически. 
Выбран паллетоукладчик -  BK2000S.

**Comment by Aizeren** [comment]
Задача перенесена в #7
