### ISSUE TITLE
Проверка, есть ли крышка

### ISSUE THREAD

**Issue by tanya525625** [Aizeren/Tikkurila-project#16]
Решить: что лучше? Купить новое оборудование, в котором встроено программное обеспечение по проверке наличия крышки. Или самим разработать способ проверки?

**Comment by Dima793** [comment]
Проверять только на наличие или ещё и на правильную сборку (криво и/или не до конца накручена)?

**Comment by Dima793** [comment]
Для решения проблемы контроля наличия крышек решено использовать диффузионный оптический датчик, поскольку он используется для аналогичной задачи в пищевой промышленности - контроля наличия крышек на бутылках.
![default](https://user-images.githubusercontent.com/17815003/49618537-a52d1680-f9c1-11e8-9743-b3d22c9dabec.jpg)

Такой датчик состоит из излучателя и приёмника, установленных в одном корпусе. Луч света инфракрасного спектра от излучателя попадает на контролируемый объект (в нашем случае - канистру) и, отражаясь от него, попадает в приемник, вызывая изменение выходного сигнала датчика. Таким образом определяется точное расстояние до объекта.

Датчик устанавливается над линией подачи канистр и направляется вниз. Происходит постоянное считывание показаний и контроль за их последовательностью расстояний объектов от датчика:
1. Расстояние больше, чем до нижней точки верхнего края канистры - датчик направлен между канистрами.
2. Расстояние до верхнего края начала канистры - очередная канистра начала заезжать под датчик.
3. Расстояние до крышки канистры - крышка ровно под датчиком.
4. Расстояние до верхнего края канистры в области сразу после крышки - крышка выехала из-под датчика.
5. Любое расстояние, не превышающее расстояние до нижней точки верхнего края канистры - остальная часть верхнего края канистры, пока она не выйдет из-под датчика.
Программное обеспечение должно отслеживать нарушение перехода из 2 состояние в 3 для определения наличия крышки и из 3 состояния в 4 для определения правильности закрученности крышки - при отсутствии крышки или перекошенности её края в начале начала состояние 3 не будет достигнуто (расстояние до датчика будет больше или меньше соответственно), а при перекошенности крышки в других местах после перехода в состояние 3 расстояние до датчика немного уменьшится перед переходом в состояние 4.

При обнаружении нарушения роботу будет отдан сигнал, что канистра, которая приедет через время t, зависящее от удалённости датчика от робота и скорости подачи канистр, не имеет закрученной надлежащим образом крышки. К моменту подачи этой канистры робот должен прервать работу с текущим паллетом, приготовить соответствующую насадку  и занять нужную позицию. При поступлении этой канистры робот должен отставить её в сторону, в неиспользуемое для других операций пространство. Предполагаемое место помечено на схеме зелёным.
![default](https://user-images.githubusercontent.com/17815003/49617164-2386ba00-f9bc-11e8-8db9-91cae68d566e.PNG)

Возможные изменения:
1. Датчик можно установить непосредственно на манипуляторе робота, на отдельном или дополнительно на уже существующий.
Это уменьшило бы используемое комплексом пространство.
Не входит в план, поскольку значительно усложняет конструкцию манипулятора и увеличивает объём работ для робота, а следовательно и время их выполнения.
2. Отслеживание последовательность состояний сигнала от датчика можно заменить отслеживанием того, что сигнал соответствует определённому значению (расстоянию до крышки) в определённые периоды времени (во время прохождения крышки под датчиком, определяемое скоростью движения канистр и диаметром крышки).
Это упростило бы задачу разработки программного обеспечения.
Не входит в план, поскольку при наличии небольших случайных промежутков между канистрами и возможных отклонений в длине самих канистр возникает отклонение от расчётного положения крышки относительно датчика, и это отклонение накапливается в процессе непрерывной работы, что может привести к неправильному срабатыванию системы на каждой канистре, начиная с какого-то момента каждого периода непрерывной работы.

Решено использовать датчик OV A43A-31P-150-LZ от компании "ТЕКО".
https://teko-com.ru/katalog/opticheskie-datchiki/optic-po-parametram/ov-a43a-31p-150-lz.html
Причины выбора данного датчика:
1. Простота и надёжность.
2. Малая стоимость - около $21.5 (без НДС), что на порядок дешевле сложных систем.
3. Наличие у производителя необходимых аксессуаров: креплений, соединителей и пр.
4. Достаточная дальность действия - 150мм, что позволяет статично закрепить датчик на высоте 350мм над линией подачи канистр и использовать его для проверки всех типов канистр.
5. Защита по стандарту IP67, удовлетворяющая требованиям пожаробезопасности.
6. Низкие требования к окружающей среде - допустимая освещенность 6000 люкс и диапазон рабочих температур -15°С...+65°С, что позволит в будущем, при необходимости, использовать такую систему даже в намного более сложных условиях, например, в полностью автоматизированном неотапливаемом цеху.
7. Поддержка отечественного производителя.
