### ISSUE TITLE
Создание модели в Blender

### ISSUE THREAD

**Issue by Aizeren** [Aizeren/Tikkurila-project#2]
Исполнитель: Екатерина

**Comment by KKastaneda** [comment]
**Описание задачи:**
Составить 3D-модель модернизируемого участка линии производства.

**Comment by Aizeren** [comment]
Модель демонстрирует процесс работы манипулятора с 3л и 10л канистрами. Алгоритм работы с 5л канистрами аналогичен алгоритму работы с 3л, так что его я отдельно воспроизводить не стала. Визуализирован способ загрузки паллет и их подачи на линию. Позже загружу видео

**Comment by Aizeren** [comment]
[Видео](https://www.youtube.com/watch?v=nKwcI3v_1Fo&feature=youtu.be)
[Картинка](https://pp.userapi.com/c846220/v846220805/147196/zUtxNFr2Q7M.jpg) (Здесь я уже изменила контур безопасности, так что на видео он другой, но на пополнение паллет это не влияет)
