### ISSUE TITLE
Калькулятор прибыли: документация

### ISSUE THREAD

**Issue by Aizeren** [Aizeren/Tikkurila-project#3]

**Comment by KKastaneda** [comment]
**Описание задачи:**
Необходимо определить наиболее часто встречающиеся на различных линиях производства элементы. Здесь под "различными" линиями подразумеваются разные сферы, в которых работает производство, например: автомобилестроение, пр-во стройматериалов, краски - чего угодно. Нужно также понять, как эти элементы связаны друг с другом, если такие связи есть и выделить две группы: встречающиеся на неавтоматизированных линиях; встречающиеся на автоматизированных линиях.

**Ожидаемый результат:**
Гугл-док со списком выявленных элементов производственных линий, с указанием, на каких (автоматизированных/не автоматизированных) производствах каждых из элементов встречается.

**Comment by KKastaneda** [comment]
Вот пример финплана:
[Пример ФП.xlsx](https://github.com/Aizeren/Tikkurila-project/files/2469105/default.xlsx)

**Comment by tanya525625** [comment]
Составлена первая версия документации для калькулятора прибыли:
