### ISSUE TITLE
Разработать план на интенсив

### ISSUE THREAD

**Issue by Aizeren** [Aizeren/Tikkurila-project#5]

**Comment by KKastaneda** [comment]
**Описание задачи:**
Составить план работы на неделю интенсива по учебной практике - 22.10 - 28.10

**Comment by KKastaneda** [comment]
Поступила неделя провести неделю интенсива в ПУНКЕ, так как почти все живут здесь, только Дмитрий будет входить по разовому пропуску.

**Comment by Aizeren** [comment]
Решение: Вт, ср в ПУНКе, остальные дни на факультете.

**Comment by KKastaneda** [comment]
Кратко: на недеде мы будем собираться только в ПУНКе, план по дням в процессе разработки.
